version: '3.8'

services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    ports:
      - "7001:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.2

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    ports:
      - "7002:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.3

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    ports:
      - "7003:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.4

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    ports:
      - "7004:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.5

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    ports:
      - "7005:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.6

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    ports:
      - "7006:7000"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7000"]
    networks:
      redis-cluster:
        ipv4_address: 172.30.0.7

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
